apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: e2e-argo-demo
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/stmcallister/e2e-argo-demo.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: e2e-demo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: